# Generated by Django 3.1.3 on 2020-11-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20201114_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, height_field='hieght_field', null=True, upload_to='media/', width_field='widt_field'),
        ),
        migrations.AddField(
            model_name='user',
            name='width_fiels',
            field=models.IntegerField(default=0),
        ),
    ]
