# Generated by Django 3.1.3 on 2020-11-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20201114_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=False, upload_to='media/'),
        ),
    ]
