# Generated by Django 3.1.3 on 2020-12-02 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
